services:
  source-s3:
    image: bitnami/minio:2022.12.7
    container_name: "source_etl_storage"
    restart: unless-stopped
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - s3_data:/data
    environment:
      MINIO_ROOT_USER: "${S3_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${S3_ROOT_PASSWORD}"

  destination-db:
    image: postgres:14
    restart: unless-stopped
    container_name: "destination_etl_database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

  notebook:
    image: "etl_jupyter_notebook"
    build: .
    command: "jupyter notebook --allow-root"
    restart: unless-stopped
    ports:
      - "8888:8888"

volumes:
  s3_data:
  postgres_data:
