services:
  storage:
    image: bitnami/minio:2022.12.7
    container_name: "storage"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
    environment:
      MINIO_ROOT_USER: "${S3_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${S3_ROOT_PASSWORD}"

  db:
    image: postgres:14
    restart: unless-stopped
    container_name: "db"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  notebook:
    image: "etl_jupyter_notebook"
    build: .
    command: "jupyter notebook --allow-root --ip 0.0.0.0 --port 8888 --NotebookApp.token='' --NotebookApp.password=''"
    restart: unless-stopped
    ports:
      - "8888:8888"

    volumes:
      - .:/app
    depends_on:
      - db
      - storage
volumes:
  storage_data:
  postgres_data:
